name: CI - Trivy
on:
  pull_request:

concurrency:
  group: pr-trivy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    name: Security
    uses: dnlopes/Reusable.Workflows/.github/workflows/trivy-scan.yaml@v1
    permissions:
      contents: read
      pull-requests: write # needed for PR comments
      statuses: write # needed for setting the status of the PR

